# Generated by Django 4.1.7 on 2023-04-07 01:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0002_rename_user_currentuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CurrentUser",
            new_name="User",
        ),
    ]
